define([
	"./Vvveb",
	"./BlocksGroup",
	"./Blocks",
	"./Builder",
	"./CodeEditor",
	"./ComponentsGroup",
	"./Components",
	"./FileManager",
	"./Gui",
	"./inputs",
	"./tmpl",
	"./Undo",
	"./WysiwygEditor",
	"./blocks/bootstrap4",
	"./components/bootstrap4",
	"./components/server",
	"./components/widgets",
	"./plugins/codemirror",
	"./plugins/google-fonts",
	"./plugins/jszip"
],function(Vvveb){
	return Vvveb;
});